/*
 * This file is part of lekhika nepali input method.
 * Copyright (c) 2023 khumnath <mail.khumnath.com.np>
 * Released under the terms of the MIT license.
 */
/*jshint browser:true */
var rules = {
  '##': 'Symbols',
    '.': '।',
    ':': 'ः',
    '~': '‌',
    '_': '‌',
    '^': '्',
    'H': 'ः',
    '\\': '्',
    '*': 'ं',
 'Ree': 'ृ',
    'M': 'ं',
    'MM': 'ँ',
    '**': 'ँ',
    '##1': 'Numbers',
    '1': '१',
    '2': '२',
    '3': '३',
    '4': '४',
    '5': '५',
    '6': '६',
    '7': '७',
    '8': '८',
    '9': '९',
    '0': '०',
    '##2': 'Vowels',
    'a': 'अ',
    'a1': 'आ',
    'a2': 'ए',
    'aa': 'आ',
    'A': 'आ',
    'A1': 'ए',
    'i': 'इ',
    'i1': 'ई',
    'i2': 'ऐ',
    'ii': 'ई',
    'I': 'ई',
    'I1': 'ऐ',
    'ee': 'ई',
    'u': 'उ',
    'u1': 'ऊ',
    'u2': 'यु',
    'uu': 'ऊ',
    'oo': 'ऊ',
    'U': 'ऊ',
    'Ri': 'ऋ',
    'Lri': 'ऌ',
    'lri': 'ऌ',
    'lree': 'ॡ',
    'e': 'ए',
    'e1': 'इ',
    'E': 'ए',
    'E1': 'इ',
    'ai': 'ऐ',
    'o': 'ओ',
    'au': 'औ',
    'am': 'अं',
    'aM': 'अं',
    'aH': 'अः',
    'aum': 'ॐ',
    'k': 'क्',
    'K': 'ख्',
    'kh': 'ख्',
    'g': 'ग्',
    'G': 'घ्',
    'gh': 'घ्',
    'ng': 'ङ्',
    'c': 'च्',
    'ch': 'च्',
    'chh': 'छ्',
    'Ch': 'छ्',
    'j': 'ज्',
    'jh': 'झ्',
    'J': 'झ्',
    'jn': 'ञ्',
    'T': 'ट्',
    'Th': 'ठ्',
    'D': 'ड्',
    'Dh': 'ढ्',
    'N': 'ण्',
    't': 'त्',
    'th': 'थ्',
    'd': 'द्',
    'dh': 'ध्',
    'n': 'न्',
    'p': 'प्',
    'ph': 'फ्',
    'f': 'फ्',
    'b': 'ब्',
    'bh': 'भ्',
    'B': 'भ्',
    'm': 'म्',
    'y': 'य्',
    'r': 'र्',
    'l': 'ल्',
    'w': 'व्',
    'v': 'व्',
    'sh': 'श्',
    'Sh': 'ष्',
    's': 'स्',
    'h': 'ह्',
    'ksh': 'क्ष्',
    'ks': 'क्स्',
    'tr': 'त्र्',
    'jnj': 'ज्ञ्',
    'ka': 'क',
    'Ka': 'ख',
    'kha': 'ख',
    'ga': 'ग',
    'Ga': 'घ',
    'gha': 'घ',
    'nga': 'ङ',
    'ca': 'च',
    'cha': 'च',
    'chha': 'छ',
    'Cha': 'छ',
    'ja': 'ज',
    'jha': 'झ',
    'Ja': 'झ',
    'jna': 'ञ',
    'Ta': 'ट',
    'Tha': 'ठ',
    'Da': 'ड',
    'Dha': 'ढ',
    'Na': 'ण',
    'ta': 'त',
    'tha': 'थ',
    'da': 'द',
    'dha': 'ध',
    'na': 'न',
    'pa': 'प',
    'pha': 'फ',
    'fa': 'फ',
    'ba': 'ब',
    'bha': 'भ',
    'Ba': 'भ',
    'ma': 'म',
    'ya': 'य',
    'ra': 'र',
    'la': 'ल',
    'wa': 'व',
    'va': 'व',
    'sha': 'श',
    'Sha': 'ष',
    'sa': 'स',
    'ha': 'ह',
    'ksha': 'क्ष',
    'ksa': 'क्स',
    'tra': 'त्र',
    'jnja': 'ज्ञ',
    'Ri1': 'ऋ',
    'kaa': 'का',
    'ki': 'कि',
    'kee': 'की',
    'ku': 'कु',
    'koo': 'कू',
    'kRi': 'कृ',
    'kRee': 'कॄ',
    'ke': 'के',
    'kai': 'कै',
    'ko': 'को',
    'kau': 'कौ',
    'Kaa': 'खा',
    'Ki': 'खि',
    'Kee': 'खी',
    'Ku': 'खु',
    'Koo': 'खू',
    'KRi': 'खृ',
    'KRee': 'खॄ',
    'Ke': 'खे',
    'Kai': 'खै',
    'Ko': 'खो',
    'Kau': 'खौ',
    'khaa': 'खा',
    'khi': 'खि',
    'khee': 'खी',
    'khu': 'खु',
    'khoo': 'खू',
    'khRi': 'खृ',
    'khRee': 'खॄ',
    'khe': 'खे',
    'khai': 'खै',
    'kho': 'खो',
    'khau': 'खौ',
    'gaa': 'गा',
    'gi': 'गि',
    'gee': 'गी',
    'gu': 'गु',
    'goo': 'गू',
    'gRi': 'गृ',
    'gRee': 'गॄ',
    'ge': 'गे',
    'gai': 'गै',
    'go': 'गो',
    'gau': 'गौ',
    'Gaa': 'घा',
    'Gi': 'घि',
    'Gee': 'घी',
    'Gu': 'घु',
    'Goo': 'घू',
    'GRi': 'घृ',
    'GRee': 'घॄ',
    'Ge': 'घे',
    'Gai': 'घै',
    'Go': 'घो',
    'Gau': 'घौ',
    'ghaa': 'घा',
    'ghi': 'घि',
    'ghee': 'घी',
    'ghu': 'घु',
    'ghoo': 'घू',
    'ghRi': 'घृ',
    'ghRee': 'घॄ',
    'ghe': 'घे',
    'ghai': 'घै',
    'gho': 'घो',
    'ghau': 'घौ',
    'ngaa': 'ङा',
    'ngi': 'ङि',
    'ngee': 'ङी',
    'ngu': 'ङु',
    'ngoo': 'ङू',
    'ngRi': 'ङृ',
    'ngRee': 'ङॄ',
    'nge': 'ङे',
    'ngai': 'ङै',
    'ngo': 'ङो',
    'ngau': 'ङौ',
    'caa': 'चा',
    'ci': 'चि',
    'cee': 'ची',
    'cu': 'चु',
    'coo': 'चू',
    'cRi': 'चृ',
    'cRee': 'चॄ',
    'ce': 'चे',
    'cai': 'चै',
    'co': 'चो',
    'cau': 'चौ',
    'chaa': 'चा',
    'chi': 'चि',
    'chee': 'ची',
    'chu': 'चु',
    'choo': 'चू',
    'chRi': 'चृ',
    'chRee': 'चॄ',
    'che': 'चे',
    'chai': 'चै',
    'cho': 'चो',
    'chau': 'चौ',
    'chhaa': 'छा',
    'chhi': 'छि',
    'chhee': 'छी',
    'chhu': 'छु',
    'chhoo': 'छू',
    'chhRi': 'छृ',
    'chhRee': 'छॄ',
    'chhe': 'छे',
    'chhai': 'छै',
    'chho': 'छो',
    'chhau': 'छौ',
    'Chaa': 'छा',
    'Chi': 'छि',
    'Chee': 'छी',
    'Chu': 'छु',
    'Choo': 'छू',
    'ChRi': 'छृ',
    'ChRee': 'छॄ',
    'Che': 'छे',
    'Chai': 'छै',
    'Cho': 'छो',
    'Chau': 'छौ',
    'jaa': 'जा',
    'ji': 'जि',
    'jee': 'जी',
    'ju': 'जु',
    'joo': 'जू',
    'jRi': 'जृ',
    'jRee': 'जॄ',
    'je': 'जे',
    'jai': 'जै',
    'jo': 'जो',
    'jau': 'जौ',
    'jhaa': 'झा',
    'jhi': 'झि',
    'jhee': 'झी',
    'jhu': 'झु',
    'jhoo': 'झू',
    'jhRi': 'झृ',
    'jhRee': 'झॄ',
    'jhe': 'झे',
    'jhai': 'झै',
    'jho': 'झो',
    'jhau': 'झौ',
    'Jaa': 'झा',
    'Ji': 'झि',
    'Jee': 'झी',
    'Ju': 'झु',
    'Joo': 'झू',
    'JRi': 'झृ',
    'JRee': 'झॄ',
    'Je': 'झे',
    'Jai': 'झै',
    'Jo': 'झो',
    'Jau': 'झौ',
    'jnaa': 'ञा',
    'jni': 'ञि',
    'jnee': 'ञी',
    'jnu': 'ञु',
    'jnoo': 'ञू',
    'jnRi': 'ञृ',
    'jnRee': 'ञॄ',
    'jne': 'ञे',
    'jnai': 'ञै',
    'jno': 'ञो',
    'jnau': 'ञौ',
    'Taa': 'टा',
    'Ti': 'टि',
    'Tee': 'टी',
    'Tu': 'टु',
    'Too': 'टू',
    'TRi': 'टृ',
    'TRee': 'टॄ',
    'Te': 'टे',
    'Tai': 'टै',
    'To': 'टो',
    'Tau': 'टौ',
    'Thaa': 'ठा',
    'Thi': 'ठि',
    'Thee': 'ठी',
    'Thu': 'ठु',
    'Thoo': 'ठू',
    'ThRi': 'ठृ',
    'ThRee': 'ठॄ',
    'The': 'ठे',
    'Thai': 'ठै',
    'Tho': 'ठो',
    'Thau': 'ठौ',
    'Daa': 'डा',
    'Di': 'डि',
    'Dee': 'डी',
    'Du': 'डु',
    'Doo': 'डू',
    'DRi': 'डृ',
    'DRee': 'डॄ',
    'De': 'डे',
    'Dai': 'डै',
    'Do': 'डो',
    'Dau': 'डौ',
    'Dhaa': 'ढा',
    'Dhi': 'ढि',
    'Dhee': 'ढी',
    'Dhu': 'ढु',
    'Dhoo': 'ढू',
    'DhRi': 'ढृ',
    'DhRee': 'ढॄ',
    'Dhe': 'ढे',
    'Dhai': 'ढै',
    'Dho': 'ढो',
    'Dhau': 'ढौ',
    'Naa': 'णा',
    'Ni': 'णि',
    'Nee': 'णी',
    'Nu': 'णु',
    'Noo': 'णू',
    'NRi': 'णृ',
    'NRee': 'णॄ',
    'Ne': 'णे',
    'Nai': 'णै',
    'No': 'णो',
    'Nau': 'णौ',
    'taa': 'ता',
    'ti': 'ति',
    'tee': 'ती',
    'tu': 'तु',
    'too': 'तू',
    'tRi': 'तृ',
    'tRee': 'तॄ',
    'te': 'ते',
    'tai': 'तै',
    'to': 'तो',
    'tau': 'तौ',
    'thaa': 'था',
    'thi': 'थि',
    'thee': 'थी',
    'thu': 'थु',
    'thoo': 'थू',
    'thRi': 'थृ',
    'thRee': 'थॄ',
    'the': 'थे',
    'thai': 'थै',
    'tho': 'थो',
    'thau': 'थौ',
    'daa': 'दा',
    'di': 'दि',
    'dee': 'दी',
    'du': 'दु',
    'doo': 'दू',
    'dRi': 'दृ',
    'dRee': 'दॄ',
    'de': 'दे',
    'dai': 'दै',
    'do': 'दो',
    'dau': 'दौ',
    'dhaa': 'धा',
    'dhi': 'धि',
    'dhee': 'धी',
    'dhu': 'धु',
    'dhoo': 'धू',
    'dhRi': 'धृ',
    'dhRee': 'धॄ',
    'dhe': 'धे',
    'dhai': 'धै',
    'dho': 'धो',
    'dhau': 'धौ',
    'naa': 'ना',
    'ni': 'नि',
    'nee': 'नी',
    'nu': 'नु',
    'noo': 'नू',
    'nRi': 'नृ',
    'nRee': 'नॄ',
    'ne': 'ने',
    'nai': 'नै',
    'no': 'नो',
    'nau': 'नौ',
    'paa': 'पा',
    'pi': 'पि',
    'pee': 'पी',
    'pu': 'पु',
    'poo': 'पू',
    'pRi': 'पृ',
    'pRee': 'पॄ',
    'pe': 'पे',
    'pai': 'पै',
    'po': 'पो',
    'pau': 'पौ',
    'phaa': 'फा',
    'phi': 'फि',
    'phee': 'फी',
    'phu': 'फु',
    'phoo': 'फू',
    'phRi': 'फृ',
    'phRee': 'फॄ',
    'phe': 'फे',
    'phai': 'फै',
    'pho': 'फो',
    'phau': 'फौ',
    'faa': 'फा',
    'fi': 'फि',
    'fee': 'फी',
    'fu': 'फु',
    'foo': 'फू',
    'fRi': 'फृ',
    'fRee': 'फॄ',
    'fe': 'फे',
    'fai': 'फै',
    'fo': 'फो',
    'fau': 'फौ',
    'baa': 'बा',
    'bi': 'बि',
    'bee': 'बी',
    'bu': 'बु',
    'boo': 'बू',
    'bRi': 'बृ',
    'bRee': 'बॄ',
    'be': 'बे',
    'bai': 'बै',
    'bo': 'बो',
    'bau': 'बौ',
    'bhaa': 'भा',
    'bhi': 'भि',
    'bhee': 'भी',
    'bhu': 'भु',
    'bhoo': 'भू',
    'bhRi': 'भृ',
    'bhRee': 'भॄ',
    'bhe': 'भे',
    'bhai': 'भै',
    'bho': 'भो',
    'bhau': 'भौ',
    'Baa': 'भा',
    'Bi': 'भि',
    'Bee': 'भी',
    'Bu': 'भु',
    'Boo': 'भू',
    'BRi': 'भृ',
    'BRee': 'भॄ',
    'Be': 'भे',
    'Bai': 'भै',
    'Bo': 'भो',
    'Bau': 'भौ',
    'maa': 'मा',
    'mi': 'मि',
    'mee': 'मी',
    'mu': 'मु',
    'moo': 'मू',
    'mRi': 'मृ',
    'mRee': 'मॄ',
    'me': 'मे',
    'mai': 'मै',
    'mo': 'मो',
    'mau': 'मौ',
    'yaa': 'या',
    'yi': 'यि',
    'yee': 'यी',
    'yu': 'यु',
    'yoo': 'यू',
    'yRi': 'यृ',
    'yRee': 'यॄ',
    'ye': 'ये',
    'yai': 'यै',
    'yo': 'यो',
    'yau': 'यौ',
    'raa': 'रा',
    'ri': 'रि',
    'ree': 'री',
    'ru': 'रु',
    'roo': 'रू',
    'rRi': 'रृ',
    'rRee': 'रॄ',
    're': 'रे',
    'rai': 'रै',
    'ro': 'रो',
    'rau': 'रौ',
    'laa': 'ला',
    'li': 'लि',
    'lee': 'ली',
    'lu': 'लु',
    'loo': 'लू',
    'lRi': 'लृ',
    'lRee': 'लॄ',
    'le': 'ले',
    'lai': 'लै',
    'lo': 'लो',
    'lau': 'लौ',
    'waa': 'वा',
    'wi': 'वि',
    'wee': 'वी',
    'wu': 'वु',
    'woo': 'वू',
    'wRi': 'वृ',
    'wRee': 'वॄ',
    'we': 'वे',
    'wai': 'वै',
    'wo': 'वो',
    'wau': 'वौ',
    'vaa': 'वा',
    'vi': 'वि',
    'vee': 'वी',
    'vu': 'वु',
    'voo': 'वू',
    'vRi': 'वृ',
    'vRee': 'वॄ',
    've': 'वे',
    'vai': 'वै',
    'vo': 'वो',
    'vau': 'वौ',
    'shaa': 'शा',
    'shi': 'शि',
    'shee': 'शी',
    'shu': 'शु',
    'shoo': 'शू',
    'shRi': 'शृ',
    'shRee': 'शॄ',
    'she': 'शे',
    'shai': 'शै',
    'sho': 'शो',
    'shau': 'शौ',
    'Shaa': 'षा',
    'Shi': 'षि',
    'Shee': 'षी',
    'Shu': 'षु',
    'Shoo': 'षू',
    'ShRi': 'षृ',
    'ShRee': 'षॄ',
    'She': 'षे',
    'Shai': 'षै',
    'Sho': 'षो',
    'Shau': 'षौ',
    'saa': 'सा',
    'si': 'सि',
    'see': 'सी',
    'su': 'सु',
    'soo': 'सू',
    'sRi': 'सृ',
    'sRee': 'सॄ',
    'se': 'से',
    'sai': 'सै',
    'so': 'सो',
    'sau': 'सौ',
    'haa': 'हा',
    'hi': 'हि',
    'hee': 'ही',
    'hu': 'हु',
    'hoo': 'हू',
    'hRi': 'हृ',
    'hRee': 'हॄ',
    'he': 'हे',
    'hai': 'है',
    'ho': 'हो',
    'hau': 'हौ',
    'kshaa': 'क्षा',
    'kshi': 'क्षि',
    'kshee': 'क्षी',
    'kshu': 'क्षु',
    'kshoo': 'क्षू',
    'kshRi': 'क्षृ',
    'kshRee': 'क्षॄ',
    'kshe': 'क्षे',
    'kshai': 'क्षै',
    'ksho': 'क्षो',
    'kshau': 'क्षौ',
    'ksaa': 'क्सा',
    'ksi': 'क्सि',
    'ksee': 'क्सी',
    'ksu': 'क्सु',
    'ksoo': 'क्सू',
    'ksRi': 'क्सृ',
    'ksRee': 'क्सॄ',
    'kse': 'क्से',
    'ksai': 'क्सै',
    'kso': 'क्सो',
    'ksau': 'क्सौ',
    'traa': 'त्रा',
    'tri': 'त्रि',
    'tree': 'त्री',
    'tru': 'त्रु',
    'troo': 'त्रू',
    'trRi': 'त्रृ',
    'trRee': 'त्रॄ',
    'tre': 'त्रे',
    'trai': 'त्रै',
    'tro': 'त्रो',
    'trau': 'त्रौ',
    'jnjaa': 'ज्ञा',
    'jnji': 'ज्ञि',
    'jnjee': 'ज्ञी',
    'jnju': 'ज्ञु',
    'jnjoo': 'ज्ञू',
    'jnjRi': 'ज्ञृ',
    'jnjRee': 'ज्ञॄ',
    'jnje': 'ज्ञे',
    'jnjai': 'ज्ञै',
    'jnjo': 'ज्ञो',
    'jnjau': 'ज्ञौ',
};

/**
 * Bind Lekhika to the input field
 */
function lekhika(widget, options) {
	var pattern, patternStart, tabCount;

	widget.enabled = options && options.enabled || false;

	if (widget.enabled) {
		widget.className = widget.className + ' lekhika';
	}

	function isToggleEvent(event) {
		var keyCode;

		keyCode = event.keyCode || event.which;
		return (keyCode === 77 && event.ctrlKey);
	}

	function listen() {
		widget.onkeydown = function (event) {
			if (isToggleEvent(event)) {
				widget.enabled = !widget.enabled;
				if (widget.enabled) {
					widget.className = widget.className + ' lekhika';
				} else {
					widget.className = widget.className.replace('lekhika', '');
					return;
				}
			} else {
				var keyCode = event.keyCode || event.which;
				if (keyCode === 9) { // backspace
					keyPressHandler(event);
				}
			}
		};

		function keyPressHandler(event) {
			if (widget.enabled) {
				return transliterate(event);
			} else {
				return true;
			}
		}
		widget.onkeypress = keyPressHandler;
	}

	function isExplorer() {
		return (document.selection && document.selection.createRange().isEqual);
	}

	function transliterate(event) {
		var stepback, pos, char, range, cursorLoc, scrollTop, kCode = event.keyCode || event.which;

		if (kCode == 8) { //backspace
			pattern = pattern.replace(/aAeEiIoOuU0-9/g, '');
			tabCount = 1;
			return;
		}
		if (event.ctrlKey || event.altKey || event.metaKey) {
			return true;
		}
		char = String.fromCharCode(kCode);
		pos = widget.selectionStart;
		if (kCode === 9) { /*Tab key*/
			tabCount++;
			if (pattern !== null || pattern !== '') {
				if (tabCount === 2) {
					pattern = pattern + tabCount;
				} else {
					if (rules[pattern.substring(0, pattern.length - 1) + tabCount]) {
						pattern = pattern.substring(0, pattern.length - 1) + tabCount;
					} else {
						tabCount = 1;
						pattern = pattern.substring(0, pattern.length - 1);
					}
				}
			}
		} else {
			pattern = pattern + char;
		}
		if (pattern.length > 5) {
			pattern = '';
			tabCount = 1;
		}
		if (tabCount >= 2) {
			event.preventDefault();
		}
		var mal = rules[pattern];
		if (!mal) {
			pattern = char;
			tabCount = 1;
			patternStart = widget.selectionStart;
			mal = rules[pattern];
		}
		if (mal) {
			if (isExplorer()) {
				range = document.selection.createRange();
				stepback = range - patternStart;
				range.moveStart('character', -stepback);
				range.text = mal;
				range.collapse(false);
				range.select();
				return false;
			} else {
				scrollTop = widget.scrollTop;
				cursorLoc = widget.selectionStart;
				stepback = cursorLoc - patternStart;
				widget.value = widget.value.substr(0, patternStart) + mal + widget.value.substr(widget.selectionEnd, widget.value.length);
				widget.scrollTop = scrollTop;
				widget.selectionStart = cursorLoc + mal.length - stepback;
				widget.selectionEnd = cursorLoc + mal.length - stepback;
				return false;
			}
		}
		if (kCode === 9) {
			return false;
		}
		return true;
	}

	listen();
}